name: Atualizar Horários

on:
  schedule:
    - cron: '0 4,16 * * *'   # Roda todo dia às 04:00 e 16:00 UTC (ajuste o fuso se precisar)
  workflow_dispatch:          # Permite rodar manualmente

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run update script
        run: python scripts/atualizar_horarios.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --cached --quiet || git commit -m "Atualiza horários via GitHub Actions"
          git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}@github.com/coisasdeitupeva/horarios-site.git
          git push origin main
